// server/services/fileService.ts
import fs from 'fs/promises';
import path from 'path';
import { Logger } from '@/utils/logger/logger';
import { CodeGenerationResult } from './ai/code_gen'; // Import the interface

/**
 * Applies the code changes generated by the AI to the repository.
 * WARNING: This directly modifies files based on AI output. Use with extreme caution!
 */
export async function applyCodeChanges(repoPath: string, changes: CodeGenerationResult): Promise<void> {
    Logger.logInfo(`Applying ${changes.files.length} file change(s) to ${repoPath}`);

    for (const fileChange of changes.files) {
        const fullPath = path.resolve(repoPath, fileChange.filePath); // Use resolve for absolute path
        const dirName = path.dirname(fullPath);

        Logger.logInfo(`Processing [${fileChange.action}] for file: ${fileChange.filePath}`);

        try {
            // Ensure target directory exists
            await fs.mkdir(dirName, { recursive: true });

            if (fileChange.action === 'delete') {
                // Check if file exists before deleting
                try {
                    await fs.unlink(fullPath);
                    Logger.logInfo(`Deleted file: ${fullPath}`);
                } catch (unlinkError: any) {
                    if (unlinkError.code === 'ENOENT') {
                        Logger.logWarn(`File not found for deletion, skipping: ${fullPath}`);
                    } else {
                        throw unlinkError; // Re-throw other unlink errors
                    }
                }
            } else { // create or update
                await fs.writeFile(fullPath, fileChange.content, 'utf-8');
                Logger.logInfo(`Wrote/Updated file: ${fullPath}`);
            }
        } catch (error: any) {
            Logger.logError(`Failed to apply change to ${fileChange.filePath}:`, error.message);
            // Decide if one failure should stop the whole process
            throw new Error(`Failed to apply code changes to ${fileChange.filePath}`);
        }
    }
    Logger.logInfo("Finished applying code changes.");
}

/** Creates a temporary directory for cloning */
export async function createTempDir(basePath: string): Promise<string> {
    try {
        // Ensure base temp directory exists
        await fs.mkdir(basePath, { recursive: true });
        // Create a unique subdirectory
        const tempPath = await fs.mkdtemp(path.join(basePath, 'repo-'));
        Logger.logInfo(`Created temporary directory: ${tempPath}`);
        return tempPath;
    } catch (error: any) {
        Logger.logError("Failed to create temporary directory:", error.message);
        throw new Error("Could not create temporary directory for cloning.");
    }
}

/** Removes a directory recursively */
export async function removeDir(dirPath: string): Promise<void> {
    Logger.logInfo(`Removing directory: ${dirPath}`);
    try {
        await fs.rm(dirPath, { recursive: true, force: true });
        Logger.logInfo(`Successfully removed directory: ${dirPath}`);
    } catch (error: any) {
        // Log error but don't necessarily crash the whole process if cleanup fails
        Logger.logError(`Failed to remove directory ${dirPath}:`, error.message);
    }
}
