


import { z } from 'zod';

// Define the Zod schema corresponding to the Mongoose AccountSchema
export type Account = {
    name: string,
    profilePicture: string,
    permissions: [],
    role: string,
    firstTime: boolean,
}
export const ZodAccountSchema = z.object({
    // name: Mongoose String, required: true
    name: z.string({
        required_error: "Name is required", // Custom error message
        invalid_type_error: "Name must be a string",
    }).min(1, { message: "Name cannot be empty" }), // Enforce non-empty string

    // profilePicture: Mongoose String, required: false, default: "..."
    profilePicture: z.string({
        invalid_type_error: "Profile picture must be a string URL",
    })
        .url({ message: "Profile picture must be a valid URL" }) // Validate it's a URL
        .optional() // Make it optional in the input
        .default("https://www.gravatar.com/avatar"), // Zod handles default during parsing

    // permissions: Mongoose Array, required: true
    // Assuming it's an array of strings, adjust z.string() if elements have a different type
    permissions: z.array(z.string(), {
        required_error: "Permissions are required",
        invalid_type_error: "Permissions must be an array of strings",
    }).nonempty({ message: "Permissions array cannot be empty" }), // Or remove if empty is allowed

    // role: Mongoose Array, required: true
    // Assuming it's an array of strings, adjust z.string() if elements have a different type
    role: z.array(z.string(), {
        required_error: "Role is required",
        invalid_type_error: "Role must be an array of strings",
    }).nonempty({ message: "Role array cannot be empty" }), // Or remove if empty is allowed

    // firstTime: Mongoose Boolean, required: true (Corrected typo from 'require')
    firstTime: z.boolean({
        required_error: "firstTime flag is required",
        invalid_type_error: "firstTime must be a boolean",
    }),

    // Note: Mongoose's _id, createdAt, updatedAt are typically NOT included
    // in the Zod schema used for INPUT validation (e.g., API request body),
    // as they are generated by MongoDB/Mongoose.
});

// Infer the TypeScript type directly from the Zod schema
// This type represents the data structure Zod expects and validates.
export type AccountInput = z.infer<typeof ZodAccountSchema>;
